# Generated by Django 5.1.5 on 2025-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_answer_es_faq_answer_fr_faq_answer_ta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_te',
            field=models.TextField(blank=True, null=True),
        ),
    ]
